C:\Users\Groot\AppData\Local\Programs\Python\Python39\python.exe C:/Users/Groot/IdeaProjects/Python/Python--Pandas/With-Pandas-File-Validation-if-Column-exists/With-Pandas-File-Validation-if-Column-exists.py
Index(['Series_reference', 'Period', 'Data_value', 'STATUS'], dtype='object')

Does the column 'ASHISH' exists in the CSV file ? False
Does the column 'Period' exists in the CSV file ? True

Process finished with exit code 0
